// Copyright 2021 Takashi Toyoshima <toyoshim@gmail.com>.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#if !defined(__JVSIO_NODE_H__)
#define __JVSIO_NODE_H__

#include <stdbool.h>
#include <stdint.h>

#include "jvsio_client.h"
#include "jvsio_common.h"

// JVSIO provides JVS (Jamma Video Standard 3.0) I/O transport,
// differential serial at 115.2Kbps, 8-bits, 1-start/stop bits, non parity.
// This library can not use with the Serial library because RXI is used
// internally.
// Incomoing data is analyzed by the hardware serial peripheral, RXI.
// The library just reads data from Data+ pin, but ignores Data-.
// Outgoint data is generated by hand-crafted code because the hardware
// does not support differential serial output.

void JVSIO_init(uint8_t nodes);

// For client nodes.
uint8_t* JVSIO_getNextCommand(uint8_t* len, uint8_t* node);
uint8_t* JVSIO_getNextSpeculativeCommand(uint8_t* len, uint8_t* node);
void JVSIO_pushReport(uint8_t report);
void JVSIO_sendUnknownStatus();
bool JVSIO_isBusy();

#if !defined(__NO_JVS_HOST__)
// For hosts.
bool JVSIO_host();
void JVSIO_sync();
#endif

#endif  // !defined(__JVSIO_NODE_H__)