name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Submodule update
      run: git submodule update --init
    - name: Build tests
      run: |
        cd test
        make node_test host_test
    - name: Run tests
      run: |
        cd test
        ./node_test
        ./host_test
